# v0.0.2
name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      BLOB_SAS: ${{ secrets.BLOB_TOKEN }}
      VERSION_SUFFIX_UK: ""
      VERSION_SUFFIX_DM: ""
      ARTIFACT_URL: ""
      PACKAGE_SERVER: "ghcr.io/virtocommerce/"
      DEMO_MANAGER_CONTAINER: "platform-demo-manager"
      UI_KIT_CONTAINER: "platform-ui-kit"

    steps:
    - uses: actions/checkout@v2    
      with:
        fetch-depth: 0

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - name: Install dependencies
      run: |
        npm install
        
    - name: Get Image Version Of Demo Manager
      uses: VirtoCommerce/vc-github-actions/get-image-version@master
      id: imageDM
      with:
        projectType: theme
        path: "./packages/demo-manager"

    - name: Get Image Version Of UI Kit
      uses: VirtoCommerce/vc-github-actions/get-image-version@master
      id: imageUK
      with:
        projectType: theme
        path: "./packages/ui-kit"

    - name: Set release variables
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "VERSION_SUFFIX_UK=${{ steps.imageUK.outputs.prefix }}" >> $GITHUB_ENV
        echo "VERSION_SUFFIX_DM=${{ steps.imageDM.outputs.prefix }}" >> $GITHUB_ENV

    - name: Set release-alpha variables
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo "VERSION_SUFFIX_UK=${{ steps.imageUK.outputs.fullVersion }}" >> $GITHUB_ENV
        echo "VERSION_SUFFIX_DM=${{ steps.imageDM.outputs.fullVersion }}" >> $GITHUB_ENV

    - name: Set PR variables
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo "VERSION_SUFFIX_UK=${{ steps.imageUK.outputs.taggedVersion }}" >> $GITHUB_ENV
        echo "VERSION_SUFFIX_DM=${{ steps.imageDM.outputs.taggedVersion }}" >> $GITHUB_ENV
        
    - name: Set ARTIFACT_URL_DM
      run: |
        echo "ARTIFACT_URL_DM=${{ env.PACKAGE_SERVER }}${{ env.DEMO_MANAGER_CONTAINER }}:${{ env.VERSION_SUFFIX_DM }}" >> $GITHUB_ENV
    
    - name: Set ARTIFACT_URL_UK
      run: |
        echo "ARTIFACT_URL_UK=${{ env.PACKAGE_SERVER }}${{ env.UI_KIT_CONTAINER }}:${{ env.VERSION_SUFFIX_UK }}" >> $GITHUB_ENV
    
    - name: Build demo manager
      run: |
        npm run build

    - name: Build ui kit
      run: |
        npm run storybook-build:ui-kit
        
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Publish Docker Image For Demo Manager
      run: |
          docker build ${{ github.workspace }} --tag ${{ env.ARTIFACT_URL_DM }} -f dockerfiles/demo-manager/Dockerfile.demo
          docker push ${{ env.ARTIFACT_URL_DM }}
          
    - name: Build and Publish Docker Image For UI Kit
      run: |
          docker build ${{ github.workspace }} --tag ${{ env.ARTIFACT_URL_UK }} -f dockerfiles/ui-kit/Dockerfile.demo
          docker push ${{ env.ARTIFACT_URL_UK }}
          
    - name: CI results
      run: |
          echo "Project $GITHUB_REPOSITORY successfully build and published to $ARTIFACT_URL_DM and $ARTIFACT_URL_UK"
